from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, Uuid, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


# Deterministic names for every index, constraint and key.
#
# Without this, PostgreSQL invents its own names and Alembic cannot
# refer to them, so an autogenerated downgrade contains:
#
#     op.drop_constraint(None, 'agents', type_='foreignkey')
#                        ^^^^ unrunnable
#
# It has to be set BEFORE the first migration. Adding it later means
# renaming every constraint that already exists in the database.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


# The loading strategy every relationship uses.
#
# "raise_on_sql" means: accessing a relationship that was NOT eagerly
# loaded raises immediately, instead of quietly emitting another query.
#
# That converts the N+1 problem from a production symptom into a
# development error:
#
#     BEFORE                         AFTER
#     list 50 conversations   1 q    list 50 conversations   1 q
#     access .messages       50 q    access .messages        raises
#                          ------                            "did you
#                            51 q                             forget
#                                                             selectinload?"
#
# The fix is always the same - say what you need at query time:
#
#     select(Conversation).options(selectinload(Conversation.messages))
#
# Declared here rather than repeated on every relationship so the
# policy is one line to inspect and one line to change.
LAZY_RAISE = "raise_on_sql"


class Base(DeclarativeBase):
    """
    The declarative base every model inherits from.

    SQLAlchemy 2.0 style: subclass DeclarativeBase rather than calling
    the 1.4-era declarative_base(). Most tutorials still show the old
    form, and mixing the two produces confusing errors.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDMixin:
    """
    A UUID primary key.

    Not an auto-incrementing integer, for three reasons:

      1. /api/agents/1 invites probing for /2, /3, /4. Phase 3.11 has
         an IDOR test; sequential ids make that attack trivial to
         attempt. (The ownership check is still mandatory - this is
         defence in depth, not a replacement.)

      2. Sequential ids publish how many rows you have, which tells
         anyone who signs up twice what your growth rate is.

      3. The id exists before the INSERT, so an SSE event can name a
         row the database has not seen yet.

    Uuid is SQLAlchemy 2.0's cross-backend type; on PostgreSQL it maps
    to the native UUID column.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        primary_key=True,
        default=uuid.uuid4,
    )


class TimestampMixin:
    """
    created_at / updated_at, in UTC.

    timezone=True is not optional. Phase 2.8 already established the
    rule for ExecutionRecord: a timestamp without a timezone is a bug
    waiting for the first deployment in another region.

    server_default=func.now() means POSTGRESQL stamps the time, not
    Python. Two application servers with slightly different clocks
    would otherwise write rows that appear out of order.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
    )
