"""add pending approvals

Revision ID: 3f091f1730f2
Revises: 847a034efb67
Create Date: 2026-08-20 16:22:57.828591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f091f1730f2'
down_revision: Union[str, Sequence[str], None] = '847a034efb67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_approvals',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sa.String(length=120), nullable=False),
    sa.Column('operation', sa.String(length=16), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_pending_approvals_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_pending_approvals_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_pending_approvals_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_pending_approvals_resolved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pending_approvals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_approvals'))
    )
    op.create_index(op.f('ix_pending_approvals_agent_id'), 'pending_approvals', ['agent_id'], unique=False)
    op.create_index(op.f('ix_pending_approvals_conversation_id'), 'pending_approvals', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_pending_approvals_user_id'), 'pending_approvals', ['user_id'], unique=False)
    op.create_index('ix_pending_approvals_waiting', 'pending_approvals', ['user_id', sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pending_approvals_waiting', table_name='pending_approvals', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_pending_approvals_user_id'), table_name='pending_approvals')
    op.drop_index(op.f('ix_pending_approvals_conversation_id'), table_name='pending_approvals')
    op.drop_index(op.f('ix_pending_approvals_agent_id'), table_name='pending_approvals')
    op.drop_table('pending_approvals')
    # ### end Alembic commands ###
