"""add agent scopes and permission audit

Revision ID: 847a034efb67
Revises: c43f24dcb688
Create Date: 2026-08-20 15:17:36.986299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '847a034efb67'
down_revision: Union[str, Sequence[str], None] = 'c43f24dcb688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_audit',
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=120), nullable=True),
    sa.Column('tool_name', sa.String(length=120), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission_audit'))
    )
    op.create_index('ix_permission_audit_agent', 'permission_audit', ['agent_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_permission_audit_created_at'), 'permission_audit', ['created_at'], unique=False)
    op.create_table('agent_scopes',
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=120), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_scopes_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_agent_scopes_granted_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_scopes')),
    sa.UniqueConstraint('agent_id', 'scope', name=op.f('uq_agent_scopes_agent_id'))
    )
    op.create_index(op.f('ix_agent_scopes_agent_id'), 'agent_scopes', ['agent_id'], unique=False)
    # ### end Alembic commands ###

    # --- BACKFILL -----------------------------------------------------
    #
    # Every agent that already exists has zero rows in agent_scopes, and
    # DatabaseScopePolicy denies a tool with no covering scope. Without
    # this step, shipping the migration would silently break every agent
    # created before it - the schema change would be correct and the
    # product would stop working.
    #
    # A schema migration that leaves existing rows in an unusable state
    # is only half a migration. The data has to move too.
    #
    # WHAT IS BACKFILLED: read wildcards only, one per service the agent
    # already has tools for. That matches what a NEW agent gets, and it
    # keeps every existing agent able to do everything it could actually
    # do before - because writes were already gated behind the per-tool
    # checkbox, which defaults to off.
    #
    # WHAT IS NOT BACKFILLED: write and admin scopes. A migration must
    # never hand out a permission a human did not ask for, and an
    # upgrade script granting write access to a client's GitHub account
    # is exactly the kind of line a security review stops on. If an
    # agent really did have a write tool ticked, its owner re-grants the
    # scope deliberately - once, in the UI.
    #
    # The ':*:read' suffix travels as a BIND PARAMETER, not as a literal
    # in the SQL string. op.execute() wraps a plain string in
    # sqlalchemy.text(), where ":read" is parsed as a placeholder - so
    # the literal form fails with "a value is required for bind
    # parameter 'read'". Any string containing a colon needs this.
    op.execute(
        sa.text(
        """
        INSERT INTO agent_scopes (id, agent_id, scope, granted_at, granted_by)
        SELECT
            gen_random_uuid(),
            a.id,
            t.namespace || :read_suffix,
            now(),
            a.user_id
        FROM agents a
        JOIN (
            SELECT DISTINCT agent_id, namespace
            FROM agent_tools
            WHERE namespace <> ''
        ) t ON t.agent_id = a.id
        ON CONFLICT (agent_id, scope) DO NOTHING
        """
        ).bindparams(read_suffix=':*:read')
    )

    # The same events, in the audit log. An agent whose history starts
    # with "revoked github:*:read" and no matching grant reads like
    # tampering; recording the backfill keeps the trail complete.
    op.execute(
        """
        INSERT INTO permission_audit
            (id, agent_id, user_id, actor_user_id, action, scope,
             tool_name, ip_address, created_at)
        SELECT
            gen_random_uuid(),
            s.agent_id,
            a.user_id,
            NULL,
            'scope.granted',
            s.scope,
            NULL,
            NULL,
            now()
        FROM agent_scopes s
        JOIN agents a ON a.id = s.agent_id
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_scopes_agent_id'), table_name='agent_scopes')
    op.drop_table('agent_scopes')
    op.drop_index(op.f('ix_permission_audit_created_at'), table_name='permission_audit')
    op.drop_index('ix_permission_audit_agent', table_name='permission_audit')
    op.drop_table('permission_audit')
    # ### end Alembic commands ###
