/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check: is this process up and configured?
         *
         *     Deliberately NOT under the /api prefix. This is called by Docker,
         *     a load balancer or an uptime monitor - infrastructure, not the
         *     frontend - and those callers should not have to care how the
         *     application namespaces its routes.
         *
         *     Deliberately does NOT touch the database. "Is the process alive?"
         *     and "are its dependencies healthy?" are different questions with
         *     different responses: a dead process must be restarted, a dead
         *     database must not. A readiness check comes later, separately.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create an account and log in.
         *
         *     201, not 200: a resource was created, and the Location of that
         *     resource is the new user.
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange credentials for a token pair.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Rotate the refresh token and mint a new access token.
         *
         *     The cookie is preferred over the body: a browser sends it
         *     automatically and cannot read it, so it is the safer of the two.
         *     The body exists for API and CLI clients, which hold no cookies.
         */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the session.
         *
         *     204 whether or not the token was real. Logout is not a place to
         *     tell an unauthenticated caller whether a token existed, and a
         *     client that already lost its token should still be able to clear
         *     its cookie without seeing an error.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description The caller, as identified by their access token.
         *
         *     The entire body is `current_user` - all the work happens in the
         *     get_current_user dependency. That is the pattern every protected
         *     endpoint from Phase 3.6 onward follows.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plugins
         * @description Every service the MCP server currently exposes.
         *
         *     Nothing here is hardcoded. Add a service to the MCP server, restart,
         *     and it appears with its tools, counts and risk levels already
         *     correct - no migration, no backend change.
         */
        get: operations["list_plugins_api_plugins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Connections
         * @description This user's connections.
         *
         *     Declared BEFORE /{key} on purpose. FastAPI matches routes in
         *     declaration order, so if /{key} came first it would capture
         *     "connections" as a plugin key and this endpoint would be
         *     unreachable - a 404 that looks like a bug in the service layer.
         */
        get: operations["list_connections_api_plugins_connections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plugin */
        get: operations["get_plugin_api_plugins__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{key}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Connect
         * @description Store an encrypted credential for this service.
         *
         *     Reconnecting replaces the credential rather than failing, which is
         *     what a user means when they paste a new token.
         */
        post: operations["connect_api_plugins__key__connect_post"];
        /**
         * Disconnect
         * @description Remove this user's connection to the service.
         *
         *     404 when there was nothing to remove, so the client can tell "you
         *     are now disconnected" from "you were never connected" - a
         *     distinction that leaks nothing, because the query was already
         *     scoped to the caller.
         */
        delete: operations["disconnect_api_plugins__key__connect_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_api_agents_get"];
        put?: never;
        /**
         * Create Agent
         * @description Create an agent.
         *
         *     Tools not named in the payload get the Phase 2 default: reads on,
         *     writes off. The agent is safe the moment it exists.
         */
        post: operations["create_agent_api_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent */
        get: operations["get_agent_api_agents__agent_id__get"];
        put?: never;
        post?: never;
        /**
         * Archive Agent
         * @description Archive, not delete.
         *
         *     DELETE is still the right verb - it is what the user means - but
         *     the row survives so conversations and execution history keep
         *     pointing at something real.
         */
        delete: operations["archive_agent_api_agents__agent_id__delete"];
        options?: never;
        head?: never;
        /** Update Agent */
        patch: operations["update_agent_api_agents__agent_id__patch"];
        trace?: never;
    };
    "/api/agents/{agent_id}/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tools */
        get: operations["get_tools_api_agents__agent_id__tools_get"];
        /**
         * Set Tools
         * @description Set which tools this agent may use.
         *
         *     This endpoint is where a user grants write access. Everything the
         *     executor later allows traces back to a row written here - which is
         *     why AgentToolPolicy denies by default: a tool that was never
         *     granted here is a tool nobody consented to.
         */
        put: operations["set_tools_api_agents__agent_id__tools_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_api_agents__agent_id__conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_api_agents__agent_id__conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_api_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Conversation
         * @description A real delete. Messages and their tool executions go with it via
         *     ON DELETE CASCADE.
         */
        delete: operations["delete_conversation_api_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Conversation
         * @description Rename or archive.
         *
         *     Renaming touches updated_at but deliberately NOT last_message_at,
         *     so the sidebar order does not jump when a user tidies up a title.
         */
        patch: operations["update_conversation_api_conversations__conversation_id__patch"];
        trace?: never;
    };
    "/api/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Messages
         * @description Newest first, cursor-paginated.
         *
         *     Pass next_cursor back to get the following page. The cursor is
         *     stable across inserts, which OFFSET is not - and this endpoint is
         *     read while new messages are actively arriving.
         */
        get: operations["list_messages_api_conversations__conversation_id__messages_get"];
        put?: never;
        /**
         * Send Message
         * @description Send a message and run one complete agent turn.
         *
         *     200, not 201. A resource IS created - the assistant message - but
         *     the useful thing about this response is the answer and the
         *     timeline, not a pointer to a new URL. 201 with a Location header
         *     would be technically defensible and practically unhelpful.
         *
         *     This endpoint is synchronous: it returns when the turn is finished,
         *     which can be 5-30 seconds. Phase 3.9 adds SSE so the client can
         *     watch the tools run instead of staring at a spinner - but the
         *     non-streaming version stays, because it is what CLI clients, tests
         *     and scheduled jobs actually want.
         */
        post: operations["send_message_api_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Executions
         * @description This user's tool activity, newest first.
         *
         *     `status` is aliased because `status` is also the name of the
         *     FastAPI module imported above for status codes. The query string
         *     keeps the name a user would expect; the Python parameter avoids the
         *     shadowing bug.
         */
        get: operations["list_executions_api_executions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/executions/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Execution Stats
         * @description Counts for the dashboard tiles.
         *
         *     Declared BEFORE any "/{execution_id}" route would be. FastAPI
         *     matches in declaration order, so a path parameter registered first
         *     would swallow "/stats" and try to look up an execution with that
         *     id.
         */
        get: operations["execution_stats_api_executions_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/messages/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream Message
         * @description Run one agent turn and stream its progress as Server-Sent Events.
         *
         *     WHY POST, WHEN SSE IS USUALLY A GET
         *
         *     Phase3.md sketches `GET /stream`, and the browser's built-in
         *     EventSource only does GET. But EventSource CANNOT SET HEADERS - so
         *     it cannot send `Authorization: Bearer ...`, and this API is
         *     bearer-authenticated. The workarounds are all worse than the
         *     problem:
         *
         *         token in the query string   -> ends up in access logs and
         *                                        browser history
         *         cookie-only auth for SSE    -> a second auth mechanism to
         *                                        maintain and get wrong
         *
         *     A POST returning text/event-stream is read with fetch() and a
         *     ReadableStream, which sends headers normally. The frame format is
         *     identical; only the client API differs.
         *
         *     WHY SSE AND NOT WEBSOCKETS
         *
         *         SSE                          WebSockets
         *         one-way, server -> client    two-way
         *         plain HTTP, proxies fine     needs upgrade support
         *         auto-reconnect built in      you write reconnection
         *         trivial to load-balance      usually needs sticky sessions
         *
         *     Everything pushed here is server-to-client. The user's input is an
         *     ordinary POST body. Nothing needs a socket.
         */
        post: operations["stream_message_api_conversations__conversation_id__messages_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentCreate */
        AgentCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /** System Prompt */
            system_prompt: string;
            /**
             * Model
             * @default minimax-m3:cloud
             */
            model: string;
            /**
             * Temperature
             * @default 0.7
             */
            temperature: number;
            /** Plugins */
            plugins?: string[];
            /** Tools */
            tools?: {
                [key: string]: components["schemas"]["AgentToolWrite"];
            };
        };
        /** AgentDetail */
        AgentDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Avatar Url */
            avatar_url: string | null;
            /** Model */
            model: string;
            /** Temperature */
            temperature: number;
            /** Is Archived */
            is_archived: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Tool Count
             * @default 0
             */
            tool_count: number;
            /** Namespaces */
            namespaces?: string[];
            /** System Prompt */
            system_prompt: string;
            /** Tools */
            tools?: components["schemas"]["AgentToolRead"][];
        };
        /**
         * AgentSummary
         * @description An agent in a list. No tools - that would be an N+1 waiting.
         */
        AgentSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Avatar Url */
            avatar_url: string | null;
            /** Model */
            model: string;
            /** Temperature */
            temperature: number;
            /** Is Archived */
            is_archived: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Tool Count
             * @default 0
             */
            tool_count: number;
            /** Namespaces */
            namespaces?: string[];
        };
        /**
         * AgentToolRead
         * @description One tool as configured on one agent.
         *
         *     Combines two sources:
         *
         *       - the agent's stored row      enabled, requires_approval
         *       - Phase 2 classification      operation, risk_level, description
         *
         *     The classification half is NOT stored in the database. It is read
         *     from the live registry on every request, so a tool that gets
         *     reclassified - or removed from the MCP server - is reflected
         *     immediately instead of showing whatever was true when the agent was
         *     created.
         */
        AgentToolRead: {
            /** Tool Name */
            tool_name: string;
            /** Namespace */
            namespace: string;
            /** Enabled */
            enabled: boolean;
            /** Requires Approval */
            requires_approval: boolean;
            /** Description */
            description?: string | null;
            /** Operation */
            operation?: string | null;
            /** Risk Level */
            risk_level?: string | null;
            /**
             * Available
             * @default true
             */
            available: boolean;
        };
        /**
         * AgentToolWrite
         * @description One tool setting, as a client sends it.
         */
        AgentToolWrite: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Requires Approval */
            requires_approval?: boolean | null;
        };
        /**
         * AgentToolsUpdate
         * @description Body for PUT /agents/{id}/tools - the complete desired set.
         */
        AgentToolsUpdate: {
            /** Tools */
            tools: {
                [key: string]: components["schemas"]["AgentToolWrite"];
            };
        };
        /**
         * AgentUpdate
         * @description A PATCH body: every field optional.
         *
         *     None means "leave unchanged", which is why nothing here has a
         *     non-None default. Distinguishing "not sent" from "set to null"
         *     is the whole difference between PATCH and PUT.
         */
        AgentUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /** System Prompt */
            system_prompt?: string | null;
            /** Model */
            model?: string | null;
            /** Temperature */
            temperature?: number | null;
            /** Is Archived */
            is_archived?: boolean | null;
        };
        /**
         * ApprovalRequired
         * @description A call that was refused because nobody could confirm it.
         */
        ApprovalRequired: {
            /** Tool Name */
            tool_name: string;
            /** Operation */
            operation: string;
            /** Risk Level */
            risk_level: string;
            /** Argument Keys */
            argument_keys?: string[];
        };
        /**
         * AuthResponse
         * @description Tokens plus the user, so a client can render immediately.
         */
        AuthResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["UserRead"];
        };
        /** ChatRequest */
        ChatRequest: {
            /** Content */
            content: string;
        };
        /**
         * ChatResponse
         * @description One completed agent turn.
         *
         *     The timeline is not decoration. It is how a user understands why an
         *     answer says what it says, and it is the fastest way to see that a
         *     tool failed rather than that the model was wrong.
         */
        ChatResponse: {
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Answer */
            answer: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Rounds
             * @default 0
             */
            rounds: number;
            /**
             * Escalations
             * @default 0
             */
            escalations: number;
            /**
             * Total Tool Ms
             * @default 0
             */
            total_tool_ms: number;
            routing?: components["schemas"]["RoutingSummary"] | null;
            /** Timeline */
            timeline?: components["schemas"]["ExecutionRead"][];
            /** Approvals Required */
            approvals_required?: components["schemas"]["ApprovalRequired"][];
            /**
             * Context Truncated
             * @default false
             */
            context_truncated: boolean;
        };
        /**
         * ConnectRequest
         * @description Connect a service by pasting a credential.
         *
         *     Phase 5 replaces this with real OAuth. The table does not change -
         *     only what fills credentials_enc.
         */
        ConnectRequest: {
            /** Credential */
            credential: string;
            /** Account Label */
            account_label?: string | null;
            /** Scopes */
            scopes?: string[];
        };
        /**
         * ConnectionRead
         * @description A user's connection to one service.
         *
         *     An ALLOW-LIST, exactly like UserRead. credentials_enc is not here
         *     and must never be: returning it - even encrypted - hands an
         *     attacker the ciphertext to work on offline, and costs the user
         *     nothing to have withheld.
         */
        ConnectionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Plugin Key */
            plugin_key: string;
            /** Status */
            status: string;
            /** Account Label */
            account_label: string | null;
            /** Scopes */
            scopes: string[];
            /** Connected At */
            connected_at: string | null;
            /** Last Used At */
            last_used_at: string | null;
            /** Expires At */
            expires_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ConversationCreate */
        ConversationCreate: {
            /** Title */
            title?: string | null;
        };
        /** ConversationRead */
        ConversationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Title */
            title: string | null;
            /** Is Archived */
            is_archived: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Last Message At */
            last_message_at: string | null;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
        };
        /**
         * ConversationUpdate
         * @description PATCH: None means leave unchanged.
         */
        ConversationUpdate: {
            /** Title */
            title?: string | null;
            /** Is Archived */
            is_archived?: boolean | null;
        };
        /**
         * ExecutionListItem
         * @description One row on the executions page.
         *
         *     A SEPARATE schema from ExecutionRead, which is the timeline row
         *     inside a chat. The difference is context: inside a conversation the
         *     reader already knows which agent is talking, so the timeline does
         *     not repeat it. The executions page spans every agent, so the agent
         *     name is the first thing the row has to say.
         *
         *     Returning ExecutionRead here and "just adding a field later" is how
         *     one schema ends up serving two screens badly.
         */
        ExecutionListItem: {
            /** Id */
            id: string;
            /** Tool Name */
            tool_name: string;
            /** Namespace */
            namespace: string | null;
            /** Operation */
            operation: string;
            /** Risk Level */
            risk_level: string;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Duration Ms */
            duration_ms: number;
            /** Attempts */
            attempts: number;
            /** Approved By User */
            approved_by_user: boolean | null;
            /** Error */
            error: {
                [key: string]: unknown;
            } | null;
            /** Agent Id */
            agent_id: string | null;
            /** Conversation Id */
            conversation_id: string | null;
            /** Agent Name */
            agent_name?: string | null;
        };
        /** ExecutionPage */
        ExecutionPage: {
            /** Items */
            items: components["schemas"]["ExecutionListItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
        };
        /**
         * ExecutionRead
         * @description One tool call in the timeline.
         *
         *     Every field comes from ExecutionRecord.to_dict(). arguments is
         *     already redacted by Phase 2 - secrets replaced and long text
         *     truncated where the record is BUILT - so it is safe to return.
         */
        ExecutionRead: {
            /** Id */
            id: string;
            /** Tool Name */
            tool_name: string;
            /** Namespace */
            namespace: string | null;
            /** Operation */
            operation: string;
            /** Risk Level */
            risk_level: string;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Duration Ms */
            duration_ms: number;
            /** Attempts */
            attempts: number;
            /** Approved By User */
            approved_by_user: boolean | null;
            /** Error */
            error: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ExecutionStats
         * @description The dashboard's numbers.
         *
         *     Computed by the database with GROUP BY, not by fetching rows and
         *     counting them in Python. A user with 50,000 executions should cost
         *     one aggregate query, not 50,000 objects loaded into memory.
         */
        ExecutionStats: {
            /** Window Days */
            window_days: number;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Success
             * @default 0
             */
            success: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Denied
             * @default 0
             */
            denied: number;
            /**
             * Avg Duration Ms
             * @default 0
             */
            avg_duration_ms: number;
            /** By Tool */
            by_tool?: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MessagePage
         * @description A cursor-paginated page.
         *
         *     next_cursor is opaque. A readable ?after_id=5 would invite clients
         *     to build their own, after which the sort order could never change.
         */
        MessagePage: {
            /** Items */
            items: components["schemas"]["MessageRead"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
        };
        /** MessageRead */
        MessageRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Role */
            role: string;
            /** Content */
            content: string | null;
            /** Tool Name */
            tool_name: string | null;
            /** Routing */
            routing: {
                [key: string]: unknown;
            } | null;
            /** Token Usage */
            token_usage: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Executions */
            executions?: components["schemas"]["ExecutionRead"][];
        };
        /**
         * PluginDetail
         * @description A service, plus its full tool list.
         */
        PluginDetail: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Icon */
            icon: string;
            /** Category */
            category: string;
            /** Auth Type */
            auth_type: string;
            /** Docs Url */
            docs_url: string | null;
            /** Tool Count */
            tool_count: number;
            /** Operations */
            operations: {
                [key: string]: number;
            };
            /** Connected */
            connected: boolean;
            /** Account Label */
            account_label?: string | null;
            /** Status */
            status?: string | null;
            /** Tools */
            tools: components["schemas"]["ToolSummary"][];
        };
        /**
         * PluginSummary
         * @description A service, as it appears in the catalogue list.
         */
        PluginSummary: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Icon */
            icon: string;
            /** Category */
            category: string;
            /** Auth Type */
            auth_type: string;
            /** Docs Url */
            docs_url: string | null;
            /** Tool Count */
            tool_count: number;
            /** Operations */
            operations: {
                [key: string]: number;
            };
            /** Connected */
            connected: boolean;
            /** Account Label */
            account_label?: string | null;
            /** Status */
            status?: string | null;
        };
        /**
         * RefreshRequest
         * @description Used by API and CLI clients, which cannot hold cookies.
         *
         *     Browsers should send the refresh token as an httpOnly cookie
         *     instead, so no JavaScript can read it. The endpoint accepts either.
         */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token?: string | null;
        };
        /**
         * RegisterRequest
         * @description What a client sends to create an account.
         *
         *     Validation happens HERE, before any code runs. FastAPI rejects a
         *     body that does not match with a 422 and a field-by-field
         *     explanation, so the service layer can assume its inputs are sane.
         */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name?: string | null;
        };
        /**
         * RoutingSummary
         * @description What the router decided, for the UI and for tuning.
         *
         *     fallback_used is the field worth watching. It means the router was
         *     not confident and widened the tool set instead of narrowing it. A
         *     rising rate is the lexicon telling you what real users actually
         *     say - it is a signal, not an error.
         */
        RoutingSummary: {
            /** Services */
            services?: string[];
            /**
             * Tool Count
             * @default 0
             */
            tool_count: number;
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /**
             * Fallback Used
             * @default false
             */
            fallback_used: boolean;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /** Unmatched Tokens */
            unmatched_tokens?: string[];
        };
        /**
         * TokenPair
         * @description What a successful register / login / refresh returns.
         *
         *     token_type is "bearer" because that is what the Authorization
         *     header expects: `Authorization: Bearer <token>`.
         *
         *     expires_in lets the client refresh BEFORE the token dies, instead
         *     of discovering it by getting a 401 in the middle of a user action.
         */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /**
         * ToolSummary
         * @description One tool, as the API describes it.
         *
         *     Every field here is produced by Phase 2 classification. Nothing is
         *     hand-maintained, so a new tool arrives fully described: what it
         *     does, how dangerous it is, and whether it will ask before running.
         */
        ToolSummary: {
            /** Name */
            name: string;
            /** Title */
            title: string | null;
            /** Description */
            description: string | null;
            /** Operation */
            operation: string;
            /** Risk Level */
            risk_level: string;
            /** Read Only */
            read_only: boolean;
            /** Requires Approval */
            requires_approval: boolean;
            /** Permissions */
            permissions: string[];
        };
        /**
         * UserRead
         * @description A user, as the API returns it.
         *
         *     A SEPARATE class from the User ORM model, deliberately. Returning
         *     the ORM object directly would serialise every column it happens to
         *     have - including password_hash. That is how password hashes end up
         *     in API responses, and it happens silently the moment someone adds a
         *     column.
         *
         *     This class is an allow-list: a field that is not written here
         *     cannot be returned. Adding a secret column to the database can
         *     never leak it through this endpoint.
         */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string | null;
            /** Is Active */
            is_active: boolean;
            /** Email Verified At */
            email_verified_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    list_plugins_api_plugins_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginSummary"][];
                };
            };
        };
    };
    list_connections_api_plugins_connections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionRead"][];
                };
            };
        };
    };
    get_plugin_api_plugins__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_api_plugins__key__connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_api_plugins__key__connect_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agents_api_agents_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_api_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_api_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_agent_api_agents__agent_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_agent_api_agents__agent_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tools_api_agents__agent_id__tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_tools_api_agents__agent_id__tools_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentToolsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_agents__agent_id__conversations_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_api_agents__agent_id__conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_conversation_api_conversations__conversation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_conversations__conversation_id__messages_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_executions_api_executions_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                /** @description success | failed | denied */
                status?: string | null;
                agent_id?: string | null;
                days?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execution_stats_api_executions_stats_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_message_api_conversations__conversation_id__messages_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
